#!/usr/bin/env sh
# (c) Florian Leitner 2012.
# All rights reserved.

VERSION=0.1;

###################
## configuration ##
###################

MAVEN_REPO=${M2_REPO:-~/.m2/repository};

#################
## environment ##
#################

export CLASSPATH=\
$MAVEN_REPO/asm/asm/3.1/asm-3.1.jar:\
$MAVEN_REPO/cglib/cglib-nodep/2.2.2/cglib-nodep-2.2.2.jar:\
$MAVEN_REPO/com/drewnoakes/metadata-extractor/2.4.0-beta-1/metadata-extractor-2.4.0-beta-1.jar:\
$MAVEN_REPO/com/googlecode/mp4parser/isoparser/1.0-beta-5/isoparser-1.0-beta-5.jar:\
$MAVEN_REPO/commons-cli/commons-cli/1.2/commons-cli-1.2.jar:\
$MAVEN_REPO/commons-codec/commons-codec/1.5/commons-codec-1.5.jar:\
$MAVEN_REPO/commons-io/commons-io/1.4/commons-io-1.4.jar:\
$MAVEN_REPO/commons-lang/commons-lang/2.4/commons-lang-2.4.jar:\
$MAVEN_REPO/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:\
$MAVEN_REPO/de/l3s/boilerpipe/boilerpipe/1.1.0/boilerpipe-1.1.0.jar:\
$MAVEN_REPO/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar:\
$MAVEN_REPO/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar:\
$MAVEN_REPO/javassist/javassist/3.6.0.GA/javassist-3.6.0.GA.jar:\
$MAVEN_REPO/jdom/jdom/1.0/jdom-1.0.jar:\
$MAVEN_REPO/junit/junit/4.10/junit-4.10.jar:\
$MAVEN_REPO/jwnl/jwnl/1.3.3/jwnl-1.3.3.jar:\
$MAVEN_REPO/net/sf/scannotation/scannotation/1.0.2/scannotation-1.0.2.jar:\
$MAVEN_REPO/org/apache/commons/commons-compress/1.3/commons-compress-1.3.jar:\
$MAVEN_REPO/org/apache/geronimo/specs/geronimo-stax-api_1.0_spec/1.0.1/geronimo-stax-api_1.0_spec-1.0.1.jar:\
$MAVEN_REPO/org/apache/james/apache-mime4j-core/0.7/apache-mime4j-core-0.7.jar:\
$MAVEN_REPO/org/apache/james/apache-mime4j-dom/0.7/apache-mime4j-dom-0.7.jar:\
$MAVEN_REPO/org/apache/opennlp/opennlp-maxent/3.0.2-incubating/opennlp-maxent-3.0.2-incubating.jar:\
$MAVEN_REPO/org/apache/opennlp/opennlp-tools/1.5.2-incubating/opennlp-tools-1.5.2-incubating.jar:\
$MAVEN_REPO/org/apache/opennlp/opennlp-uima/1.5.2-incubating/opennlp-uima-1.5.2-incubating.jar:\
$MAVEN_REPO/org/apache/pdfbox/fontbox/1.6.0/fontbox-1.6.0.jar:\
$MAVEN_REPO/org/apache/pdfbox/jempbox/1.6.0/jempbox-1.6.0.jar:\
$MAVEN_REPO/org/apache/pdfbox/pdfbox/1.6.0/pdfbox-1.6.0.jar:\
$MAVEN_REPO/org/apache/poi/poi-ooxml-schemas/3.8-beta5/poi-ooxml-schemas-3.8-beta5.jar:\
$MAVEN_REPO/org/apache/poi/poi-ooxml/3.8-beta5/poi-ooxml-3.8-beta5.jar:\
$MAVEN_REPO/org/apache/poi/poi-scratchpad/3.8-beta5/poi-scratchpad-3.8-beta5.jar:\
$MAVEN_REPO/org/apache/poi/poi/3.8-beta5/poi-3.8-beta5.jar:\
$MAVEN_REPO/org/apache/tika/tika-core/1.1/tika-core-1.1.jar:\
$MAVEN_REPO/org/apache/tika/tika-parsers/1.1/tika-parsers-1.1.jar:\
$MAVEN_REPO/org/apache/uima/jVinci/2.4.0/jVinci-2.4.0.jar:\
$MAVEN_REPO/org/apache/uima/uimaj-adapter-vinci/2.4.0/uimaj-adapter-vinci-2.4.0.jar:\
$MAVEN_REPO/org/apache/uima/uimaj-core/2.4.0/uimaj-core-2.4.0.jar:\
$MAVEN_REPO/org/apache/uima/uimaj-cpe/2.4.0/uimaj-cpe-2.4.0.jar:\
$MAVEN_REPO/org/apache/uima/uimaj-document-annotation/2.4.0/uimaj-document-annotation-2.4.0.jar:\
$MAVEN_REPO/org/apache/uima/uimaj-tools/2.4.0/uimaj-tools-2.4.0.jar:\
$MAVEN_REPO/org/apache/xmlbeans/xmlbeans/2.3.0/xmlbeans-2.3.0.jar:\
$MAVEN_REPO/org/bouncycastle/bcmail-jdk15/1.45/bcmail-jdk15-1.45.jar:\
$MAVEN_REPO/org/bouncycastle/bcprov-jdk15/1.45/bcprov-jdk15-1.45.jar:\
$MAVEN_REPO/org/ccil/cowan/tagsoup/tagsoup/1.2.1/tagsoup-1.2.1.jar:\
$MAVEN_REPO/org/easymock/easymock/3.1/easymock-3.1.jar:\
$MAVEN_REPO/org/gagravarr/vorbis-java-core/0.1/vorbis-java-core-0.1-tests.jar:\
$MAVEN_REPO/org/gagravarr/vorbis-java-core/0.1/vorbis-java-core-0.1.jar:\
$MAVEN_REPO/org/gagravarr/vorbis-java-tika/0.1/vorbis-java-tika-0.1.jar:\
$MAVEN_REPO/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar:\
$MAVEN_REPO/org/objenesis/objenesis/1.2/objenesis-1.2.jar:\
$MAVEN_REPO/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar:\
$MAVEN_REPO/org/springframework/spring-core/3.0.3.RELEASE/spring-core-3.0.3.RELEASE.jar:\
$MAVEN_REPO/org/uimafit/uimafit/1.3.1/uimafit-1.3.1.jar:\
$MAVEN_REPO/rome/rome/0.9/rome-0.9.jar:\
$MAVEN_REPO/txtfnnl/txtfnnl-bin/0.1/txtfnnl-bin-0.1.jar:\
$MAVEN_REPO/txtfnnl/txtfnnl-opennlp/0.1/txtfnnl-opennlp-0.1.jar:\
$MAVEN_REPO/txtfnnl/txtfnnl-tika/0.1/txtfnnl-tika-0.1.jar:\
$MAVEN_REPO/txtfnnl/txtfnnl-uima/0.1/txtfnnl-uima-0.1.jar:\
$MAVEN_REPO/txtfnnl/txtfnnl-utils/0.1/txtfnnl-utils-0.1.jar;

#################
## main script ##
#################

help () {
    echo "usage: txtfnnl <command> [options] <arguments>";
    echo;
    echo "commands:";
    echo "  ss    - split sentences";
    echo;
    echo "Use 'txtfnnl <command> --help' to learn more about each command.";
    echo "(c) Florian Leitner 2012. All rights reserved. Version" $VERSION;
}

if [ $# -gt 0 ]; then
    cmd=$1;
    shift;
    case $cmd in
        ss) java txtfnnl.pipelines.SentenceExtractor "$@";;
        -v) echo txtfnnl-$VERSION;;
        --version) echo txtfnnl-$VERSION;;
        -h) help; exit 0;;
        --help) help; exit 0;;
        *) echo "unknown command:" $cmd; exit 1;;
    esac;
else
    help;
    exit 2;
fi;
